import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { type Paths } from "../constants";
import { type Result, ok, err } from "../types";
import { readConfig } from "./config";
import { getDefaultBranch, type GitEnv } from "./git";
import { toSlug } from "./slug";

export interface GenerateClaudeFilesResult {
  treesMd: string[];
  claudeMd: "created" | "exists";
}

export function generateClaudeFiles(
  workspace: string,
  paths: Paths,
  env?: GitEnv,
): Result<GenerateClaudeFilesResult> {
  const configResult = readConfig(paths.workspaceConfig(workspace));
  if (!configResult.ok) {
    if (configResult.code === "CONFIG_NOT_FOUND") {
      return err(`Workspace "${workspace}" not found`, "WORKSPACE_NOT_FOUND");
    }
    return configResult;
  }

  const { repos } = configResult.value;

  // Ensure .claude/ dir exists
  mkdirSync(paths.workspaceDotClaude(workspace), { recursive: true });

  // Build @-reference lines for repos that have a CLAUDE.md in their default-branch worktree
  const included: string[] = [];
  const sortedRepos = repos.slice().sort((a, b) => a.name.localeCompare(b.name));

  for (const repo of sortedRepos) {
    let branchResult;
    try {
      branchResult = getDefaultBranch(repo.path, env);
    } catch {
      continue;
    }
    if (!branchResult.ok) continue;

    const slug = toSlug(branchResult.value);
    const worktreePath = paths.worktreeDir(workspace, repo.name, slug);
    if (!existsSync(join(worktreePath, "CLAUDE.md"))) continue;

    included.push(repo.name);
  }

  // Write trees.md (always overwritten)
  const atLines = included.map(
    (name) => `@../trees/${name}/${toSlug(getDefaultBranchCached(repos, name, env))}/CLAUDE.md`,
  );
  const treesMdContent =
    "# Generated by dotclaude — do not edit manually\n" +
    (atLines.length > 0 ? atLines.join("\n") + "\n" : "");

  writeFileSync(paths.claudeTreesMd(workspace), treesMdContent);

  // Write CLAUDE.md only if it doesn't exist
  let claudeMdStatus: "created" | "exists";
  if (existsSync(paths.claudeMd(workspace))) {
    claudeMdStatus = "exists";
  } else {
    writeFileSync(paths.claudeMd(workspace), "@.claude/trees.md\n");
    claudeMdStatus = "created";
  }

  return ok({ treesMd: included, claudeMd: claudeMdStatus });
}

/** Re-derive the default branch for a repo by name (from the already-resolved list). */
function getDefaultBranchCached(
  repos: { name: string; path: string }[],
  name: string,
  env?: GitEnv,
): string {
  const repo = repos.find((r) => r.name === name);
  if (!repo) return "main";
  try {
    const result = getDefaultBranch(repo.path, env);
    return result.ok ? result.value : "main";
  } catch {
    return "main";
  }
}
