import { exists, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { type Paths } from "../constants";
import { type Result, ok, err } from "../types";
import { readConfig } from "./config";
import { getDefaultBranch, type GitEnv } from "./git";
import { toSlug } from "./slug";

export interface GenerateClaudeFilesResult {
  treesMd: string[];
  claudeMd: "created" | "exists";
}

export async function generateClaudeFiles(
  workspace: string,
  paths: Paths,
  env?: GitEnv,
): Promise<Result<GenerateClaudeFilesResult>> {
  const configResult = await readConfig(paths.workspaceConfig(workspace));
  if (!configResult.ok) {
    if (configResult.code === "CONFIG_NOT_FOUND") {
      return err(`Workspace "${workspace}" not found`, "WORKSPACE_NOT_FOUND");
    }
    return configResult;
  }

  const { repos } = configResult.value;

  // Ensure .claude/ dir exists
  await mkdir(paths.workspaceDotClaude(workspace), { recursive: true });

  // Build @-reference lines for repos that have a CLAUDE.md in their default-branch worktree
  const includedWithBranches: { name: string; branch: string }[] = [];
  const sortedRepos = repos.slice().sort((a, b) => a.name.localeCompare(b.name));

  for (const repo of sortedRepos) {
    let branchResult;
    try {
      branchResult = await getDefaultBranch(repo.path, env);
    } catch {
      continue;
    }
    if (!branchResult.ok) continue;

    const slug = toSlug(branchResult.value);
    const worktreePath = paths.worktreeDir(workspace, repo.name, slug);
    if (!(await exists(join(worktreePath, "CLAUDE.md")))) continue;

    includedWithBranches.push({ name: repo.name, branch: branchResult.value });
  }

  const included = includedWithBranches.map((r) => r.name);
  const atLines = includedWithBranches.map(
    ({ name, branch }) => `@../trees/${name}/${toSlug(branch)}/CLAUDE.md`,
  );

  // Write trees.md (always overwritten)
  const treesMdContent =
    "# Generated by dotclaude — do not edit manually\n" +
    (atLines.length > 0 ? atLines.join("\n") + "\n" : "");

  await writeFile(paths.claudeTreesMd(workspace), treesMdContent);

  // Write CLAUDE.md only if it doesn't exist
  let claudeMdStatus: "created" | "exists";
  if (await exists(paths.claudeMd(workspace))) {
    claudeMdStatus = "exists";
  } else {
    await writeFile(paths.claudeMd(workspace), "@.claude/trees.md\n");
    claudeMdStatus = "created";
  }

  return ok({ treesMd: included, claudeMd: claudeMdStatus });
}
